#!/bin/bash

# Make sure we are in the right base dir
if [ -d ./ANFS ]; then
	BASE_DIR="$PWD"
else
	BASE_DIR="${PWD}/.."
fi

# Ensure we use the right config file
MACH=$(uname -m)

if [ "$MACH" = "x86_64" ]; then
	CONFIG="kconfig-64"
elif [ "$MACH" = "i686" ]; then
	CONFIG="kconfig-32"
else
	echo "Unsupported arch $MACH!!!"
	exit 1
fi

cp $BASE_DIR/ANFS/$CONFIG $BASE_DIR/.config || exit 1

# Get the first 7 bytes of the git hash for tracking info
GVER=$(git rev-parse HEAD | head -c 7)

cd $BASE_DIR

# Compile using 3 threads
export CONCURRENCY_LEVEL=3

# Cleanup
fakeroot make-kpkg clean || exit 1
# Compile it
fakeroot make-kpkg --append_to_version "-anfs" --revision "g${GVER}" --initrd kernel_image kernel_debug kernel_headers || exit 1

cd -

